### ISSUE TITLE
License

### ISSUE THREAD

**Issue by VladUreche** [ayoungprogrammer/readAI#2]
Hi @ayoungprogrammer! I wanted to try out an idea I had some time ago starting from your project. Can I use your code, what is the license?

Btw, just for reference, both the Stanford Parser and the Nodebox Linguistics packages are distributed under GPL v2 licenses.

**Comment by ayoungprogrammer** [comment]
Added the same GPL v2 license.

Good luck!

**Comment by VladUreche** [comment]
Thank you!
