### ISSUE TITLE
Error in seemingly supported use case

### ISSUE THREAD

**Issue by kootenpv** [ayoungprogrammer/readAI#3]
Can you explain the following error:

```
Enter line: Mary ate an apple because Mary was hungry
Enter line: Why did Mary eat an Apple?

AttributeError: 'DummyNode' object has no attribute 'prev'
```

**Comment by ayoungprogrammer** [comment]
(VP ( VBD ) ( NP ) ( SBAR ) ) was not supported but I added it in my latest commit. I also added a debug flag that can be used so you can see the parse tree and see if a rule is not being matched.
